name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - '**/**'
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: .
      run: docker build . --file Dockerfile --tag tanchwa/todoist-reclaim-webhook:latest
    - name: Push the Docker image
      run: docker login -u tanchwa -p ${{ secrets.DOCKER_TOKEN }} && docker push tanchwa/todoist-reclaim-webhook:latest
